name: Check for typos and broken links

on:
  push:
    branches: [ hakyll ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Spellcheck
      run: find ./weblog/posts/ -maxdepth 1 -name "*.markdown" -exec aspell check {} \;
